version: "3.8"

services:
  jazzer:
    container_name: "jazzer"
    image: "cifuzz/jazzer"
    command: >
      --cp='/fuzzing/example.jar'
      --target_class='org.example.WebserverFuzzer'
      --coverage_report=coverage.txt
      --coverage_dump=coverage.exec
      --instrumentation_includes=java.**:org.example.*
      --instrumentation_excludes=org.example.WebserverFuzzer:java.lang.Object
      -max_len=20
      -max_total_time=60
      -dict=url_dict
      -merge_control_file=merge_control
      WebserverCorpus
    volumes:
      - ./build/libs/example-fuzzing-1.0-SNAPSHOT.jar:/fuzzing/example.jar:ro
      - ./build/merge_control:/fuzzing/merge_control:ro
      - ./build/resources/main/WebserverCorpus/:/fuzzing/WebserverCorpus
      - ./build/resources/main/url_dict:/fuzzing/url_dict