version: "3.8"

services:
  jazzer:
    container_name: "jazzer"
    build:
      context: ./jazzer-interactive-fuzz
    command: >
      /app/jazzer --cp='/fuzzing/example.jar'
                  --autofuzz=org.example.Webserver::checkUrl
                  --autofuzz_ignore=java.lang.Exception
                  --coverage_report=coverage
                  -max_len=20
                  -max_total_time=5
                  -dict=url_dict
                  WebserverCorpus
    volumes:
      - ./build/libs/example-java-1.0-SNAPSHOT.jar:/fuzzing/example.jar:ro
      - ./build/resources/main/WebserverCorpus/:/fuzzing/WebserverCorpus:ro
      - ./build/resources/main/url_dict:/fuzzing/url_dict:ro