version: "3.8"

services:
  jazzer:
    container_name: "jazzer"
    image: "cifuzz/jazzer"
    command: >
      --cp='/fuzzing/example.jar'
      --autofuzz=org.example.Webserver::checkUrl
      --autofuzz_ignore=java.lang.Exception
      --coverage_report=coverage
      -max_len=20
      -max_total_time=5
      -dict=url_dict
      -merge=1
      WebserverCorpus
      WebserverCorpusMinimized
    volumes:
      - ./build/libs/example-fuzzing-1.0-SNAPSHOT.jar:/fuzzing/example.jar:ro
      - ./build/resources/main/url_dict:/fuzzing/url_dict
      - ./build/resources/main/WebserverCorpus/:/fuzzing/WebserverCorpus
      - ./build/resources/main/WebserverCorpusMinimized/:/fuzzing/WebserverCorpusMinimized